# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(help_text='Type of notice (e.g., policy, regulation, announcement)', max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='Official reference number', max_length=100)),
                ('publication_date', models.DateField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_government_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices_government_notice',
                'ordering': ('-publication_date',),
            },
        ),
        migrations.CreateModel(
            name='NoticeImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator', models.CharField(help_text='Economic indicator affected', max_length=255)),
                ('baseline_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('projected_impact', models.DecimalField(decimal_places=4, max_digits=12)),
                ('impact_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_interval', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='notices.governmentnotice')),
            ],
            options={
                'db_table': 'notices_notice_impact',
                'ordering': ('notice', 'indicator'),
            },
        ),
        migrations.CreateModel(
            name='NoticeSectorImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(help_text='Type of impact (e.g., positive, negative, neutral)', max_length=100)),
                ('impact_score', models.DecimalField(decimal_places=2, help_text='Impact score (0-10)', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_impacts', to='notices.governmentnotice')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notice_impacts', to='sectors.sector')),
            ],
            options={
                'db_table': 'notices_notice_sector_impact',
                'ordering': ('notice', 'sector'),
            },
        ),
    ]
