# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dashboard_type', models.CharField(choices=[('EXECUTIVE', 'Executive'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor'), ('DATA_FEEDER', 'Data Feeder')], max_length=32)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Dashboard layout configuration')),
                ('widgets', models.JSONField(blank=True, default=list, help_text='List of widgets and their configurations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_dashboard',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('TABLE', 'Table'), ('KPI', 'KPI'), ('MAP', 'Map')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration')),
                ('position', models.JSONField(blank=True, default=dict, help_text='Widget position in the layout')),
                ('size', models.JSONField(blank=True, default=dict, help_text='Widget size configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='dashboard.dashboard')),
            ],
            options={
                'db_table': 'dashboard_widget',
                'ordering': ('dashboard', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Aggregated data for the widget')),
                ('refresh_time', models.DateTimeField(auto_now=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard.dashboardwidget')),
            ],
            options={
                'db_table': 'dashboard_data',
                'ordering': ('-refresh_time',),
            },
        ),
    ]
