# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=18)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, help_text='Unit price for the product on this date.', max_digits=18)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.product')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sectors.sector')),
            ],
            options={
                'db_table': 'sales_sale',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['product', 'date'], name='sal_sale_prod_date_idx'), models.Index(fields=['sector', 'date'], name='sal_sale_sect_date_idx')],
            },
        ),
    ]
