# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_costs', to='sectors.sector')),
            ],
            options={
                'db_table': 'costs_input_cost',
                'ordering': ('name',),
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='InputCostValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='costs.inputcost')),
            ],
            options={
                'db_table': 'costs_input_cost_value',
                'ordering': ('cost', 'date'),
                'indexes': [models.Index(fields=['cost', 'date'], name='cst_icv_cost_date_idx')],
            },
        ),
    ]
