# Generated by Django 5.1.6 on 2026-03-21 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Stable, machine-readable code for use in policy checks.', max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text="Logical grouping (e.g., 'sales', 'policies', 'ml').", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Constraint hints (e.g., sector scoping, read-only flags).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'governance_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ECONOMIC_ANALYST', 'Economic Analyst'), ('DATA_SCIENTIST', 'Data Scientist'), ('AUDITOR', 'Auditor'), ('EXECUTIVE_VIEWER', 'Executive Viewer'), ('DATA_FEEDER', 'Data Feeder')], help_text='Stable code used in authorization logic and policy definitions.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=True, help_text='System roles are managed via governance processes, not arbitrarily edited.')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional governance metadata (e.g., allowed scopes, risk level).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'governance_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Contextual constraints, e.g., sector IDs, indicator sets.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='governance.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='governance.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'governance_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
