# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(help_text='Type of fertilizer (e.g., NPK, Urea, etc.)', max_length=100)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fertilizers', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fertilizers', to='sectors.sector')),
            ],
            options={
                'db_table': 'inputs_fertilizer',
                'ordering': ('name',),
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(help_text='Type of fuel (e.g., diesel, petrol, etc.)', max_length=100)),
                ('unit', models.CharField(default='liter', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('energy_content', models.DecimalField(decimal_places=2, help_text='Energy content per unit (MJ)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fuels', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuels', to='sectors.sector')),
            ],
            options={
                'db_table': 'inputs_fuel',
                'ordering': ('name',),
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='InputSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_fertilizer_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_seed_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_pesticide_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_fuel_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_summaries', to='sectors.sector')),
            ],
            options={
                'db_table': 'inputs_summary',
                'ordering': ('-date', 'sector'),
                'unique_together': {('sector', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(help_text='Type of pesticide (e.g., herbicide, insecticide, etc.)', max_length=100)),
                ('unit', models.CharField(default='liter', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pesticides', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesticides', to='sectors.sector')),
            ],
            options={
                'db_table': 'inputs_pesticide',
                'ordering': ('name',),
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(help_text='Type of crop (e.g., maize, wheat, etc.)', max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('yield_per_unit', models.DecimalField(decimal_places=2, help_text='Expected yield per unit', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_seeds', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seeds', to='sectors.sector')),
            ],
            options={
                'db_table': 'inputs_seed',
                'ordering': ('name',),
                'unique_together': {('name', 'sector')},
            },
        ),
    ]
