# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SEED', 'Seed'), ('FERTILIZER', 'Fertilizer'), ('PESTICIDE', 'Pesticide'), ('HERBICIDE', 'Herbicide'), ('OTHER', 'Other')], max_length=32)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_agricultural_inputs', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agricultural_inputs', to='sectors.sector')),
            ],
            options={
                'db_table': 'agriculture_inputs_agricultural_input',
                'ordering': ('name',),
                'unique_together': {('name', 'sector', 'type')},
            },
        ),
        migrations.CreateModel(
            name='AgriculturalInputValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Unit price for the input on this date.', max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost (value * unit_price).', max_digits=18, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='agriculture_inputs.agriculturalinput')),
            ],
            options={
                'db_table': 'agriculture_inputs_agricultural_input_value',
                'ordering': ('input', 'date'),
                'indexes': [models.Index(fields=['input', 'date'], name='agr_aiv_inp_date_idx')],
            },
        ),
    ]
