# Generated by Django 5.1.6 on 2026-03-24 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'externalindicator_external_source',
            },
        ),
        migrations.CreateModel(
            name='ExternalIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='externalindicator.externalsource')),
            ],
            options={
                'db_table': 'externalindicator_indicator',
                'unique_together': {('source', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExternalIndicatorValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='externalindicator.externalindicator')),
            ],
            options={
                'db_table': 'externalindicator_indicator_value',
                'ordering': ('indicator', 'date'),
                'unique_together': {('indicator', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProviderMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_code', models.CharField(help_text='Code or endpoint identifier from the external provider', max_length=400)),
                ('date_key', models.CharField(default='date', help_text='JSON key/path for the date field in provider payloads', max_length=128)),
                ('value_key', models.CharField(default='value', help_text='JSON key/path for the value field in provider payloads', max_length=128)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Optional provider-specific mapping config')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='externalindicator.externalsource')),
                ('target_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_mappings', to='indicators.indicator')),
            ],
            options={
                'db_table': 'externalindicator_provider_mapping',
                'unique_together': {('source', 'external_code')},
            },
        ),
    ]
