# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Stable code for the indicator (e.g. 'CPI').", max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, help_text="Unit of measurement (e.g. '%', 'index').", max_length=64)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Primary data source name (e.g. statistics bureau).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional attributes, e.g. units, frequency.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'indicators_indicator',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='IndicatorVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(help_text="Free-form version label (e.g. '2025-01-release-1').", max_length=64)),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('quality_score', models.FloatField(blank=True, help_text='Optional quality metric (0-1 or percentage).', null=True)),
                ('payload_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata about the ingested dataset, not the raw data itself.')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='indicators.indicator')),
            ],
            options={
                'db_table': 'indicators_indicator_version',
                'ordering': ('-ingestion_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator')),
            ],
            options={
                'db_table': 'indicators_indicator_value',
                'ordering': ('indicator', 'date'),
                'indexes': [models.Index(fields=['indicator', 'date'], name='ind_iv_ind_date_idx')],
            },
        ),
    ]
