# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('policies', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SUBMITTED', 'Submitted for approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVALIDATED', 'Invalidated')], default='DRAFT', max_length=32)),
                ('assumptions', models.JSONField(blank=True, default=dict, help_text='Analyst assumptions and notes backing this forecast.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('accuracy_summary', models.JSONField(blank=True, default=dict, help_text='Aggregated accuracy metrics for this forecast.')),
                ('diagnostics', models.JSONField(blank=True, default=dict, help_text='Miscellaneous diagnostics (e.g. runtime info, warnings).')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_forecasts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_forecasts', to=settings.AUTH_USER_MODEL)),
                ('indicator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='indicators.indicatorversion')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='policies.policyversion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='system.datasnapshot')),
            ],
            options={
                'db_table': 'forecasts_forecast',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ForecastSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=16)),
                ('schedule_spec', models.JSONField(blank=True, default=dict, help_text='Schedule definition (e.g. cron, interval, sector scope).')),
                ('template', models.JSONField(blank=True, default=dict, help_text='Template payload for forecast generation requests.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_forecast_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forecasts_schedule',
                'ordering': ('-created_at',),
            },
        ),
    ]
