# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Stable code for the policy (e.g. 'VAT_CHANGE_2025').", max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=32)),
                ('type', models.CharField(help_text="Policy type (e.g. 'tax', 'subsidy', 'regulation').", max_length=64)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Policy-specific parameters and configuration.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional policy metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='sectors.sector')),
            ],
            options={
                'db_table': 'policies_policy',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PolicySimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('baseline_snapshot', models.CharField(help_text='DataSnapshot UUID', max_length=36)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('results', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policies_policy_simulation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PolicyImpactAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('key_findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_analyses', to=settings.AUTH_USER_MODEL)),
                ('sectors', models.ManyToManyField(blank=True, to='sectors.sector')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='policies.policysimulation')),
            ],
            options={
                'db_table': 'policies_policy_impact_analysis',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PolicySimulationComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('comparison_metrics', models.JSONField(blank=True, default=dict)),
                ('key_differences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_comparisons', to='policies.policysimulation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_comparisons', to=settings.AUTH_USER_MODEL)),
                ('simulations', models.ManyToManyField(related_name='comparisons', to='policies.policysimulation')),
            ],
            options={
                'db_table': 'policies_policy_simulation_comparison',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(help_text="Version label (e.g. 'v1.0', '2025-01').", max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=32)),
                ('implementation', models.JSONField(blank=True, default=dict, help_text='Policy implementation details for simulations.')),
                ('assumptions', models.JSONField(blank=True, default=dict, help_text='Assumptions underlying this policy version.')),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policies.policy')),
            ],
            options={
                'db_table': 'policies_policy_version',
                'ordering': ('-created_at',),
                'unique_together': {('policy', 'version_label')},
            },
        ),
        migrations.AddField(
            model_name='policysimulation',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='policies.policyversion'),
        ),
    ]
