# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role_code', models.CharField(blank=True, help_text='Primary role code of the actor at the time of the action.', max_length=64)),
                ('action', models.CharField(help_text="High-level action identifier, e.g. 'policy.update', 'role.change', 'snapshot.lock'.", max_length=128)),
                ('entity_type', models.CharField(help_text="Logical entity type, e.g. 'Policy', 'User', 'DataSnapshot'.", max_length=128)),
                ('entity_id', models.CharField(help_text='Primary identifier of the entity at the time of the action.', max_length=128)),
                ('request_method', models.CharField(blank=True, max_length=16)),
                ('request_path', models.CharField(blank=True, max_length=512)),
                ('correlation_id', models.CharField(blank=True, help_text='Per-request correlation ID injected by audit middleware.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured payload, e.g. before/after snapshots.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='aud_audlog_enttyp_entid_idx'), models.Index(fields=['timestamp'], name='aud_audlog_ts_idx'), models.Index(fields=['action'], name='aud_audlog_act_idx')],
            },
        ),
    ]
