# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasts', '0001_initial'),
        ('sectors', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('definition', models.JSONField(blank=True, default=dict, help_text='Declarative description of dataset inputs (snapshots, sectors, policies, date ranges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_dataset',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('spec', models.JSONField(blank=True, default=dict, help_text='Feature engineering specification and metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_feature_sets', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sets', to='ml.dataset')),
            ],
            options={
                'db_table': 'ml_feature_set',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ml_datasets', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_datasets', to='sectors.sector')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_datasets', to='system.datasnapshot')),
            ],
            options={
                'db_table': 'ml_ml_dataset',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(help_text='Algorithm identifier (e.g., XGBoost, LSTM, TFT).', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CANDIDATE', 'Candidate'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=32)),
                ('train_config', models.JSONField(blank=True, default=dict, help_text='Training configuration, hyperparameters, and preprocessing options.')),
                ('artifact_path', models.CharField(blank=True, help_text='Reference to persisted model artifacts (e.g. object storage path).', max_length=512)),
                ('code_version', models.CharField(blank=True, help_text='Git/SemVer identifier of training code.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_models', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ml.dataset')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ml.featureset')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_model_registry',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModelExplainability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficients', models.JSONField(blank=True, default=dict)),
                ('p_values', models.JSONField(blank=True, default=dict)),
                ('confidence_intervals', models.JSONField(blank=True, default=dict)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('adjusted_r_squared', models.FloatField(blank=True, null=True)),
                ('f_statistic', models.FloatField(blank=True, null=True)),
                ('f_p_value', models.FloatField(blank=True, null=True)),
                ('durbin_watson', models.FloatField(blank=True, null=True)),
                ('jarque_bera', models.FloatField(blank=True, null=True)),
                ('jarque_bera_p_value', models.FloatField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explainability_results', to='ml.modelregistry')),
            ],
            options={
                'db_table': 'ml_model_explainability',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('is_hpo', models.BooleanField(default=False)),
                ('hyperparameters', models.JSONField(blank=True, default=dict, help_text='Hyperparameters or search space definition.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Aggregated training/validation metrics.')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_training_jobs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_jobs', to='ml.dataset')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_jobs', to='ml.featureset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ml.modelregistry')),
            ],
            options={
                'db_table': 'ml_training_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MLDatasetRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sales', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('inflation', models.FloatField(blank=True, null=True)),
                ('fuel_cost', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('other_features', models.JSONField(blank=True, default=dict, help_text='JSON bag for additional features.')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ml.mldataset')),
            ],
            options={
                'db_table': 'ml_ml_dataset_row',
                'ordering': ('dataset', 'date'),
                'indexes': [models.Index(fields=['dataset', 'date'], name='ml_dsrw_dset_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('confidence_lower', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('confidence_upper', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('prediction_date', models.DateField()),
                ('horizon_months', models.IntegerField()),
                ('model_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='forecasts.forecast')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='ml.modelregistry')),
            ],
            options={
                'db_table': 'ml_forecast_result',
                'ordering': ('-prediction_date',),
                'unique_together': {('forecast', 'model', 'prediction_date')},
            },
        ),
    ]
