# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(default=dict)),
                ('status', models.CharField(default='COMPLETED', max_length=32)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comparison_metrics', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scenarios', models.ManyToManyField(to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=32)),
                ('type', models.CharField(help_text="Scenario type (e.g. 'baseline', 'stress_test', 'what_if').", max_length=64)),
                ('assumptions', models.JSONField(blank=True, default=dict, help_text='Scenario assumptions and parameters.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional scenario metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scenario_definitions', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_definitions', to='sectors.sector')),
            ],
            options={
                'db_table': 'scenarios_scenario_definition',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(help_text="Version label (e.g. 'v1.0', '2025-01').", max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=32)),
                ('implementation', models.JSONField(blank=True, default=dict, help_text='Scenario implementation details for simulations.')),
                ('assumptions', models.JSONField(blank=True, default=dict, help_text='Assumptions underlying this scenario version.')),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scenario_versions', to=settings.AUTH_USER_MODEL)),
                ('scenario_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scenarios.scenariodefinition')),
            ],
            options={
                'db_table': 'scenarios_scenario_version',
                'ordering': ('-created_at',),
                'unique_together': {('scenario_definition', 'version_label')},
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarioversion'),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
            ],
        ),
    ]
