# Generated by Django 5.1.6 on 2026-03-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Stable code for the sector (e.g. 'AGR', 'MAN', 'SER').", max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional sector metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sectors', to=settings.AUTH_USER_MODEL)),
                ('parent_sector', models.ForeignKey(blank=True, help_text='Parent sector for hierarchical organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sectors', to='sectors.sector')),
            ],
            options={
                'db_table': 'sectors_sector',
                'ordering': ('code',),
            },
        ),
    ]
